version: '3'

tasks:
  build:
    cmd: |
      bun run ninja
      echo "FINISHED COMPILATION!!!!"
    sources:
      - '**/*.h'
      - '**/*.hpp'
      - '**/*.c'
      - '**/*.cpp'
      - build.sh
      - exclude: build/**/*
